# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/desktop/shuluo/project/4kmania/constraints_display.xdc

# IP: ip/img0_1/img0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==img0 || ORIG_REF_NAME==img0} -quiet] -quiet
