# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/desktop/shuluo/project/4kmania/project_1/project_1.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 8
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/desktop/shuluo/project/4kmania/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/desktop/shuluo/project/4kmania/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/desktop/shuluo/project/4kmania/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files D:/desktop/shuluo/project/4kmania/output.coe
add_files D:/desktop/shuluo/project/4kmania/img0.coe
add_files D:/desktop/shuluo/project/4kmania/air.coe
add_files D:/desktop/shuluo/project/4kmania/lacie_beatmap.coe
add_files D:/desktop/shuluo/project/4kmania/pandora.coe
add_files D:/desktop/shuluo/project/4kmania/lacie.coe
add_files d:/desktop/shuluo/project/4kmania/lacie1.coe
add_files d:/desktop/shuluo/project/4kmania/dango.coe
add_files d:/desktop/shuluo/project/4kmania/dango_beatmap.coe
add_files d:/desktop/shuluo/project/4kmania/clannad.coe
read_verilog -library xil_defaultlib {
  D:/desktop/shuluo/project/4kmania/clk_div.v
  D:/desktop/shuluo/project/4kmania/display.v
  D:/desktop/shuluo/project/4kmania/display_test.v
  D:/desktop/shuluo/project/4kmania/game_control.v
  D:/desktop/shuluo/project/4kmania/kb_top.v
  D:/desktop/shuluo/project/4kmania/keyboard1.v
  D:/desktop/shuluo/project/4kmania/vgac.v
  D:/desktop/shuluo/project/4kmania/top.v
  D:/desktop/shuluo/project/4kmania/DisplaySync.v
  D:/desktop/shuluo/project/4kmania/Hex2Seg.v
  D:/desktop/shuluo/project/4kmania/HexTo8SEG.v
  D:/desktop/shuluo/project/4kmania/Mux4to1b4.v
  D:/desktop/shuluo/project/4kmania/P2S_io.v
  D:/desktop/shuluo/project/4kmania/DisplayNumber.v
  D:/desktop/shuluo/project/4kmania/MyMC14495.v
  D:/desktop/shuluo/project/4kmania/Mux4to1.v
  D:/desktop/shuluo/project/4kmania/dispnum.v
  D:/desktop/shuluo/project/4kmania/SSeg_Dev.v
  D:/desktop/shuluo/project/4kmania/AND_GATE.v
  D:/desktop/shuluo/project/4kmania/OR_GATE_4_INPUTS.v
  D:/desktop/shuluo/project/4kmania/img.v
  D:/desktop/shuluo/project/4kmania/pwm_gen.v
  D:/desktop/shuluo/project/4kmania/get_pitch.v
  D:/desktop/shuluo/project/4kmania/music_gen.v
}
read_ip -quiet D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/img0_1/img0.xci
set_property used_in_implementation false [get_files -all d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/img0_1/img0_ooc.xdc]

read_ip -quiet D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/img1/img1.xci
set_property used_in_implementation false [get_files -all d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/img1/img1_ooc.xdc]

read_ip -quiet D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/music0/music0.xci
set_property used_in_implementation false [get_files -all d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/music0/music0_ooc.xdc]

read_ip -quiet D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/music1/music1.xci
set_property used_in_implementation false [get_files -all d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/music1/music1_ooc.xdc]

read_ip -quiet D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/box_rom1/box_rom1.xci
set_property used_in_implementation false [get_files -all d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/box_rom1/box_rom1_ooc.xdc]

read_edif D:/desktop/shuluo/project/4kmania/P2S.edf
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/desktop/shuluo/project/4kmania/constraints_display.xdc
set_property used_in_implementation false [get_files D:/desktop/shuluo/project/4kmania/constraints_display.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/utils_1/imports/synth_1/kb_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7k160tffg676-2L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
