# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/img1/img1.xci
# IP: The module: 'img1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/img1/img1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/desktop/shuluo/project/4kmania/project_1/project_1.srcs/sources_1/ip/img1/img1.xci
# IP: The module: 'img1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/desktop/shuluo/project/4kmania/project_1/project_1.gen/sources_1/ip/img1/img1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
